//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineExamSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestXPaper
    {
        public int Id { get; set; }
        public Nullable<int> RegistirationId { get; set; }
        public Nullable<int> TestXQuestionId { get; set; }
        public Nullable<int> ChoiceId { get; set; }
        public Nullable<int> MarkScored { get; set; }
    
        public virtual Choice Choice { get; set; }
        public virtual Registiration Registiration { get; set; }
        public virtual TestXQuestion TestXQuestion { get; set; }
    }
}
